trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  # EJEMPLO para Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm test
    displayName: 'Run tests'

  - script: |
      npm run build || echo "No build script"
    displayName: 'Build (optional)'
